### ISSUE TITLE
Question about config that allows villagers enter trains but not move them

### ISSUE THREAD

**Issue by Jacold** [bergerhealer/TrainCarts#326]
##### Spigot version: paper 332

<hr>

#### Problem or bug:

DefaultTrainProperties.yml:
```yaml
default:
  soundEnabled: true
  displayName: ''
  allowPlayerTake: true
  requirePoweredMinecart: false
  trainCollision: true
  collisionDamage: 1.0
  keepChunksLoaded: false
  speedLimit: 0.4
  waitDistance: 0.0
  suffocation: true
  killMessage: ''
  banking:
    strength: 0.0
    smoothness: 10.0
  slowDown: true
  allowManualMovement: true
  tickets: []
  collision:
    players: DEFAULT
    misc: ENTER
    train: LINK
    block: DEFAULT
  blockTypes: ''
  blockOffset: unset
  owners: []
  ownerPermissions: []
  tags: []
  allowPlayerEnter: true
  allowPlayerExit: true
  invincible: false
  isPublic: true
  pickUp: false
  exitOffset: 
    ==: Vector
    x: 0.0
    y: 0.0
    z: 0.0
  exitYaw: 0.0
  exitPitch: 0.0
  driveSound: ''
  blockBreakTypes: []
  destination: ''
  enterMessage: ''
  spawnItemDrops: true
admin:
  soundEnabled: true
  displayName: ''
  allowPlayerTake: false
  requirePoweredMinecart: false
  trainCollision: true
  collisionDamage: 1.0
  keepChunksLoaded: false
  speedLimit: 0.4
  waitDistance: 0.0
  suffocation: true
  killMessage: ''
  banking:
    strength: 0.0
    smoothness: 10.0
  slowDown: true
  allowManualMovement: false
  tickets: []
  collision:
    players: DEFAULT
    misc: ENTER
    train: LINK
    block: DEFAULT
  blockTypes: ''
  blockOffset: unset
  owners: []
  ownerPermissions: []
  tags: []
  allowPlayerEnter: true
  allowPlayerExit: true
  invincible: false
  isPublic: true
  pickUp: false
  exitOffset: 
    ==: Vector
    x: 0.0
    y: 0.0
    z: 0.0
  exitYaw: 0.0
  exitPitch: 0.0
  driveSound: ''
  blockBreakTypes: []
  destination: ''
  enterMessage: ''
  spawnItemDrops: true
spawner:
  soundEnabled: true
  displayName: ''
  allowPlayerTake: false
  requirePoweredMinecart: false
  trainCollision: true
  collisionDamage: 1.0
  keepChunksLoaded: false
  speedLimit: 0.4
  waitDistance: 0.0
  suffocation: true
  killMessage: ''
  banking:
    strength: 0.0
    smoothness: 10.0
  slowDown: true
  allowManualMovement: false
  tickets: []
  collision:
    players: DEFAULT
    misc: ENTER
    train: LINK
    block: DEFAULT
  blockTypes: ''
  blockOffset: unset
  owners: []
  ownerPermissions: []
  tags: []
  allowPlayerEnter: true
  allowPlayerExit: true
  invincible: false
  isPublic: true
  pickUp: false
  exitOffset: 
    ==: Vector
    x: 0.0
    y: 0.0
    z: 0.0
  exitYaw: 0.0
  exitPitch: 0.0
  driveSound: ''
  blockBreakTypes: []
  destination: ''
  enterMessage: ''
  spawnItemDrops: true
```
config.yml
```yaml
#> This is the configuration file of TrainCarts
#> In here you can tweak TrainCarts to what you want
#> For more information, you can visit the following websites:
#> http://www.minecraftwiki.net/wiki/Bukkit/TrainCarts
#> http://forums.bukkit.org/threads/traincarts.29491/

# Path or online download URL to the resource pack to use
# Using 'server' makes it use server.properties (default)
# Using 'default' or empty makes it use no resource pack at all
resourcePack: server

# Properties of the link between the carts of a train
linkProperties:
  # The distance between two carts in a train
  cartDistanceGap: 0.5
  # The distance between two carts above which they lose linkage and disconnect
  cartDistanceGapMax: 2.5
  # Factor at which the gap is maintained, based on train velocity
  cartDistanceForcer: 0.1
  # Factor at which the gap is maintained, always active
  # When set to nonzero, will cause carts to move at standstill
  cartDistanceForcerConstant: 0.0

# Whether or not the combined carts (powered/storage minecarts) break up into two items
breakCombinedCarts: false

# A performance boost to give to powered minecarts (0 = normal speed)
poweredCartBoost: 0.1

# The boosting factor of powered rails (default = 0.06)
poweredRailBoost: 0.06

# The maximum velocity (blocks/tick) a minecart can possibly have set
maxVelocity: 5.0

# The multiplier used to slow down minecarts
# Normal is the default, slow is when the minecart is meant to slow down.
slowDownMultiplier:
  normal: 0.997
  slow: 0.96

# The maximum allowed enter radius for enter signs
maxEnterDistance: 50.0

# The maximum allowed ejection distance for eject signs
maxEjectDistance: 10.0

# The amount of velocity stations give when launching trains
launchForce: 10.0

# Destroys all existing minecarts on startup and shutdown of the plugin
destroyAllOnShutdown: false

# Settings used when carts collide with entities
collision:
  # If train owners are ignored
  ignoreOwners: false
  # If global train owners are ignored
  ignoreGlobalOwners: false
  # The amount of force at which minecarts push away others
  pushAwayForce: 0.2

# Whether or not all minecarts spawned on the server turn into TrainCarts' Minecarts
# Note that the TrainCart placement permission is then no longer active
allMinecartsAreTrainCarts: false

# Whether or not powered minecarts obtain their coal from attached storage minecarts
useCoalFromStorageCart: false

# Whether or not the player that places a minecart is set owner
setOwnerOnPlacement: false

# Whether or not a hissing sound is made when trains stop at a station
playSoundAtStation: true

# What style of launching to use in stations and launcher sign systems by default. Possible values:
# - 'linear': gradually switches from one motion speed to another at a linear rate
# - 'bezier': uses a bezier curve (ease in-out), resulting in slower changes in motion at start/end of launch
launchFunction: bezier

# Whether or not chunks are only kept loaded when the train is moving
keepChunksLoadedOnlyWhenMoving: false

# Whether to enable or cancel collisions with blocks above minecarts
# Some constructions depend on these block collisions to block minecarts
# If these collisions are unwanted, they can be turned off here
enableCeilingBlockCollision: true

# Advanced: Whether trains use a different way of server->client synchronization
# With this enabled, trains are expected to move smoother with less bumping
# With this disabled, no smoothing is applied. Only disable it if it causes problems/incompatibility
useNetworkSynchronizer: true

# Enable or disable seeing yourself in third-person on vertical rails
# Turning this off only causes this mode to activate when going upside-down
enableSeatThirdPersonView: false

# The maximum length a detector region (between two detectors) can be
maxDetectorLength: 2000

# The maximum amount of minecart items that can be stacked in one item
maxMinecartStackSize: 64

# The maximum radius chest/furnace sign systems look for the needed blocks
maxTransferRadius: 5

# The default radius chest/furnace sign systems look for the needed blocks
defaultTransferRadius: 2

# Whether or not empty minecarts slow down faster than occupied minecarts
slowDownEmptyCarts: false

# Whether storage minecarts get fuel when launching from stations
refillAtStations: true

# Whether destroying or entering minecarts is made easier to do
# When optimized, block / air clicks are intercepted and handled as clicks with minecarts instead
optimizeInteraction: true

# When set to true, players will be able to break minecarts with a single slap
# 
# No item drops are spawned for minecarts destroyed this way. Minecart contents ARE dropped.
# They can still select minecarts by crouching and then slapping the minecart
# 
# When set to false, players will never instantly destroy minecarts and they will have to break it as if in survival.
instantCreativeDestroy: true

# Whether upside-down rail functionality is enabled on the server
# When disabled, minecarts can not be rotated upside-down
allowUpsideDownRails: true

# Before TrainCarts v1.12.2-v1 speed limiting was done on each individual axis
# This had a big impact on air physics, because it never made a good ellipse fall
# This was changed to preserving the motion vector direction when doing speed limiting
# Slight changes may have occurred in curves, slopes and through-air physics
# To restore the old limiting system, set this option to True
legacySpeedLimiting: false

# Whether players (with build permissions) can edit existing rails by right-clicking on them
allowRailEditing: true

# Velocity factor to apply when a player tries to move a cart using movement controls
manualMovementFactor: 0.1

# The currency Ticket signs will display in messages, %value% represents the displayed value
currencyFormat: '%value% Dollars'

# Whether trains can be teleported to the nether (or back) when rails are laid close to the portals
allowNetherTeleport: true

# The delay (in ticks) between ejecting and re-entering by collision (e.g. mobs auto-entering carts)
collisionReEnterDelay: 100
# Whether powered activator rails eject players inside Minecarts (Vanilla)
# If activator rails are used for decoration purposes, this should be disabled
activatorEjectEnabled: true

# A list of world names where TrainCarts should be disabled
# World names are not case-sensitive
disabledWorlds:
  - DefaultWorld1
  - DefaultWorld2

# The block materials that can be broken using minecarts
# Players with the admin block break permission can use any type
# Others have to use one from this list
allowedBlockBreakTypes:
  - LEGACY_CROPS
  - LEGACY_LOG

# Whether or not to show item animations when transferring items
showTransferAnimations: true

# Whether a crafting table must exist when crafting items inside a storage minecart
# When this is set to false and no crafting table is nearby, no item transfer animations are shown
craftingRequireWorkbench: true

# Several shortcuts you can use on announce signs (text is replaced)
messageShortcuts:
  welcome: &eWelcome to &f

# Several shortcuts you can use on switcher and detector signs (text is replaced)
statementShortcuts:
  diamond: i@diamond

# Several shortcuts you can use on signs to set the items
itemShortcuts:
  fuel: ''
  heatable: ''
  armor: golden_helmet;golden_leggings;diamond_helmet;legacy_chainmail_helmet;legacy_leather_leggings;legacy_leather_chestplate;legacy_leather_boots;legacy_iron_boots;iron_chestplate;legacy_gold_chestplate;legacy_diamond_chestplate;iron_boots;legacy_diamond_boots;legacy_gold_helmet;leather_leggings;diamond_chestplate;legacy_iron_chestplate;leather_chestplate;legacy_leather_helmet;diamond_boots;legacy_diamond_leggings;golden_chestplate;chainmail_chestplate;golden_boots;turtle_helmet;chainmail_boots;legacy_gold_leggings;chainmail_helmet;chainmail_leggings;legacy_iron_helmet;legacy_gold_boots;diamond_leggings;legacy_chainmail_leggings;legacy_chainmail_chestplate;leather_boots;iron_helmet;legacy_chainmail_boots;legacy_iron_leggings;legacy_diamond_helmet;iron_leggings;leather_helmet
  sword: wooden_sword;stone_sword;iron_sword;golden_sword;iron_sword;diamond_sword;legacy_wood_sword;legacy_stone_sword;legacy_iron_sword;legacy_gold_sword;legacy_iron_sword;legacy_diamond_sword
  boots: leather_boots;iron_boots;golden_boots;diamond_boots;chainmail_boots;legacy_leather_boots;legacy_iron_boots;legacy_gold_boots;legacy_diamond_boots;legacy_chainmail_boots
  leggins: leather_leggings;iron_leggings;golden_leggings;diamond_leggings;chainmail_leggings;legacy_leather_leggings;legacy_iron_leggings;legacy_gold_leggings;legacy_diamond_leggings;legacy_chainmail_leggings
  chestplate: leather_chestplate;iron_chestplate;golden_chestplate;diamond_chestplate;chainmail_chestplate;legacy_leather_chestplate;legacy_iron_chestplate;legacy_gold_chestplate;legacy_diamond_chestplate;legacy_chainmail_chestplate
  helmet: leather_helmet;iron_helmet;golden_helmet;diamond_helmet;chainmail_helmet;turtle_helmet;legacy_leather_helmet;legacy_iron_helmet;legacy_gold_helmet;legacy_diamond_helmet;legacy_chainmail_helmet

# Enables parsing signs with (train), as well as [train]
# This makes it easier to write signs with a Mac keyboard layout
parseParentheses: true

# Requires all neighbouring chunks to be loaded too before
# initializing the redstone state (powered or not) of signs in a chunk
# True can prevent crashes and helps performance by avoiding recursive chunk loads
# False will make sure signs initialize sooner and respond to redstone faster
initRedstoneWithRadius: true

# Sets whether only powered switcher signs without statements on them
# actively switch tracks to lead trains towards their destination
# When true, only [+train] switcher signs do pathfinding logic
# When false, the original behavior is used, where any switcher sign handles path finding
# False will allow switching of trains overriding standard path finding
onlyPoweredEmptySwitchersDoPathfinding: false

# Default attachment animations that can be applied to the base of all trains
defaultAnimations:
  rotate:
    nodes:
      - t=0.25
      - t=0.25 yaw=90.0
      - t=0.25 yaw=180.0
      - t=0.25 yaw=270.0
      - t=0.0 yaw=360.0
  roll:
    nodes:
      - t=0.25
      - t=0.25 roll=90.0
      - t=0.25 roll=180.0
      - t=0.25 roll=270.0
      - t=0.0 roll=360.0
  pitch:
    nodes:
      - t=0.25
      - t=0.25 pitch=90.0
      - t=0.25 pitch=180.0
      - t=0.25 pitch=270.0
      - t=0.0 pitch=360.0

# Sets whether attachment animations use tick time or wall clock time
# When false, wall clock time is used, and server lag will not slow down/speed up animations
# When true, tick time is used, and server lag will cause speed changes. Animations do stay in sync with physics
animationsUseTickTime: false

# Sets whether the player can move around by holding shift in the attachment editor
enableSneakingInAttachmentEditor: false

# Sets the interval at which all the properties of all trains on the server are saved to disk
# This saving may have a negative performance impact, as seen in the AutoSaveTask in timings
# If you do not worry about preserving this information, you can raise this interval
# A manual save can be performed using /train saveall
autoSaveInterval: 600

# Sets whether players automatically claim new saved trains that they save
# Once claimed, other players cannot overwrite the saved train, effectively protecting it
# Setting this to false will have new trains exist in public domain, and anyone can modify it
# The original owner can put the train in public domain by disclaiming it (/savedtrain [name] disclaim)
# Players (moderators) with the train.command.savedtrain.global permission are exempt
claimNewSavedTrains: false

# The hastebin server which is used to upload saved trains
# This will be used when using the /savedtrain [name] paste command
hastebinServer: https://paste.traincarts.net

# Parse signs made in Minecraft 1.7 and before without re-creating
parseOldSigns: false
```

This settings allows mobs to enter trains but it won't stand still (occupied cart will move and finally disconnect). It is possible to configure that correctly?

#### Expected behaviour:

Pushed entities will enter empty train carts but whole train should stand still and accupied carts shouldn't disconnect.

#### Steps to reproduce:

I've pasted my config, just place long track, few carts and push villager into the cart.

Have a nice day.
