### ISSUE TITLE
The player collision options does not seem to work

### ISSUE THREAD

**Issue by zicy** [bergerhealer/TrainCarts#327]
##### Spigot version: git-Spigot-56f8471-3e3818b

<hr>

#### Expected behaviour:
I expected the following config, to PUSH players away when hit by a TrainCart, but this does not happen. Instead the TrainCart just collide and stop when hitting a player.
if i change "PUSH" to "CANCEL" the minecart still stops when hitting players.

```YAML
admin:
  soundEnabled: true
  displayName: ''
  allowPlayerTake: true
  requirePoweredMinecart: false
  trainCollision: true
  collisionDamage: 0.0
  keepChunksLoaded: false
  speedLimit: 0.4
  slowDown: true
  allowManualMovement: true
  collision:
    players: PUSH
    misc: PUSH
    train: CANCEL
    npc: ENTER
    animal: ENTER
    monster: ENTER
  owners: []
  ownerPermissions: []
  tags: []
  allowPlayerEnter: true
  allowPlayerExit: true
  invincible: false
  isPublic: true
  pickUp: false
  exitOffset:
    ==: Vector
    x: 0.0
    y: 0.0
    z: 0.0
  exitYaw: 0.0
  exitPitch: 0.0
  blockBreakTypes: []
  destination: ''
  enterMessage: ''
  spawnItemDrops: true
```

#### Steps to reproduce:
Using the config above and placing a TrainCart, setting a destionation and standing in the way of TrainCart, as i tries to go to the destionation.
