### ISSUE TITLE
Spinning wheel animations go wild at speed

### ISSUE THREAD

**Issue by amalon** [bergerhealer/TrainCarts#483]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): v1.20.1-v3-SNAPSHOT (build: 1605)
- TrainCarts Version (`/train version`): v1.20.1-v3-SNAPSHOT (build: 1444)
- Server Type and Version (`/version`): git-Paper-65 (MC: 1.20.1)

----
### Description
I have animated some train wheels to spin (with pitch) when the train moves. They work great when the train moves slowly, however at speed the smaller wheels wobble like crazy (i.e. they look as if they're wobbling off center), and when going diagonally (e.g. with TC-coaster rails) the bigger wheels yaw very fast back and forth about the Y axis.

### Expected behaviour
Ideally items with a looped pitch animation should animate the same at high speed as at low speed, just faster.

### Actual behaviour
Fast animated items (pitch) rotate off center or with non-animated axes (yaw) not matching that of the train as it goes diagonally.

In the following pic the big wheels can be seen at the wrong yaw, and the small wheels at the front have at that moment sunk into the track:
![2023-09-11_00 02 33](https://github.com/bergerhealer/TrainCarts/assets/210303/e9f16a9a-4ce7-4ada-a5b1-21383c27d5fa)

Here's a stationary pic:
https://github.com/amalon/hoganfam-trains/blob/master/docs/a4.jpg

### Steps to reproduce
Create a wheel with the following animation:
````yml
            animations:
              move:
                nodes:
                  - t=0.25
                  - t=0.25 pitch=90.0
                  - t=0.25 pitch=180.0
                  - t=0.25 pitch=270.0
                  - t=0.0 pitch=360.0
                movementControlled: true
                looped: true
                speed: 0.2
                autoplay: true
````
Or use the "a4" train from the hoganfam_trains.yml saved train module and the corresponding resource pack found here: https://github.com/amalon/hoganfam-trains

Drive the train at speed along diagonal track and observe from 3rd person view.

Perhaps there is a better way to do the animation so this doesn't happen?
Or perhaps due to client side interpolation this will never work?
It'd be nice if it could work though, as spoked wheels look really odd not rotating!
