### ISSUE TITLE
Suggestion: Custom Signs

### ISSUE THREAD

**Issue by HairyDaddy** [bergerhealer/TrainCarts#81]
_I’m not sure this is the right place to post a suggestion and I apologize if it’s the case._

I’ve been looking over a plugin called mycommand recently and I realized it’s functions would be very useful if applied on TrainCarts. This plugin I’m referring to has a custom file .yml file where you can create your very own commands and permissions and deny/allow them on groupmanager/pex. I imagine a system like this would do wonders on TrainCarts and add a window of opportunities for server owners, considering you’d have the ability to make custom built-in signs and use permissions as a comparison system of sorts, thus working as a privilege system allowing us to give players a more.. "vivid experience" of what TrainCarts should feel like. Say, the plugin would be able to integrate with Autorank and allow players to have bonuses as they rank up, considering a situation where players would navigate faster if they have a higher rank:
In-Game:
[!cart]
predefined
fastercarts

.yml file:

```
fastercarts:
  sign1:
    assign: "!cart"
    type: "property"
    function: "maxspeed, 4"
  sign2:
    assign: "!cart"
    type: "launcher 50"
    function: "3"
  sign3:
   assign: "!cart"
   type: "announce"
   function: "You are allowed to travel faster!"
```

The custom permission node should be: traincarts.predefined.fastercarts

Well, this sums it up. I hope you understand where I'm trying to get at. I reckon this suggestion would generate you a lot of work.. but oh well, I have a voice, should as well use it, even when I know it’s probably not a valid point. Anyways, thank you for your time going through this post and know that you have developed the best plugin ever, I just love TrainCarts and it’s already existing features. I come here in hopes of improving what’s already the best in store.
